checks:
  php: true

filter:
  excluded_paths:
    - tests/*
    - examples/*
    - docs/*

build:
  environment:
    php: '7.1.6'
  tests:
    before:
      - 'composer self-update'
      - 'composer --install --prefer-source --no-interaction'
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
        coverage:
          file: 'clover.xml'
          format: 'clover'