checks:
  php: true

filter:
  excluded_paths:
    - tests/*
    - examples/*
    - docs/*
    - CommonTest.php

build:
  tests:
    override:
      command: 'true'

tools:
  external_code_coverage:
    timeout: 180